name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: ["main"]

jobs:
  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Simulate deploy
        run: echo "Deploying fastapi-ci-cd-demo to staging..."
